### ISSUE TITLE
Development Status?

### ISSUE THREAD

**Issue by gakonst** [OpenZeppelin/nile-rs#39]
Hi - was just wondering if this project is still being developed? Or is it on pause? Thank you!

**Comment by ericnordelo** [comment]
> Hi - was just wondering if this project is still being developed? Or is it on pause? Thank you!

It's paused for a few months, but the plan is to sunset it completely. We believe that with the ecosystem maturity and emerging tools, we can safely focus on developing the contracts library, and contribute to these other tooling projects when needed, instead of maintaining Nile, whose goal was to support the contracts library development at the beginning.

We will give a notice and update this repository accordingly soon.

**Comment by gakonst** [comment]
roger - thx!
